const AppAction = {
    LOADING_APP_START: 'LOADING_APP_START',
    CLOSE_LOADING_APP: 'CLOSE_LOADING_APP',
    LOADING_APP_POPUP_START: 'LOADING_APP_POPUP_START',
    CLOSE_LOADING_APP_POPUP: 'CLOSE_LOADING_APP_POPUP',

    FETCH_SAMPLE_1: 'FETCH_SAMPLE_1',
    FETCH_SAMPLE_1_SUCCESS: 'FETCH_SAMPLE_1_SUCCESS',
    FETCH_SAMPLE_1_ERROR: 'FETCH_SAMPLE_1_ERROR',

    FETCH_SAMPLE_2: 'FETCH_SAMPLE_2',
    FETCH_SAMPLE_2_SUCCESS: 'FETCH_SAMPLE_2_SUCCESS',
    FETCH_SAMPLE_2_ERROR: 'FETCH_SAMPLE_2_ERROR',

    FETCH_DATA: 'FETCH_DATA',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',

    ADD_DATA: 'ADD_DATA',
    ADD_DATA_SUCCESS: 'ADD_DATA_SUCCESS',

    FILL_DETAIL_DATA: 'FILL_DETAIL_DATA',
    FILL_DETAIL_DATA_SUCCESS: 'FILL_DETAIL_DATA_SUCCESS',

    FETCH_CITY_DATA: 'FETCH_CITY_DATA',
    FETCH_CITY_DATA_SUCCESS: 'FETCH_CITY_DATA_SUCCESS',

    FETCH_DIST_DATA: 'FETCH_DIST_DATA',
    FETCH_DIST_DATA_SUCCESS: 'FETCH_DIST_DATA_SUCCESS',

    FETCH_WARDS_DATA: 'FETCH_WARDS_DATA',
    FETCH_WARDS_DATA_SUCCESS: 'FETCH_WARDS_DATA_SUCCESS',

    SEARCH_DATA: 'SEARCH_DATA',
    SEARCH_DATA_SUCCESS: 'SEARCH_DATA_SUCCESS',

    DEBT_DATA: 'DEBT_DATA',
    DEBT_DATA_SUCCESS: 'DEBT_DATA_SUCCESS'

};

export default AppAction;
