const AppAction = {
    FETCH_GET_DATA: 'FETCH_GET_DATA',
    FETCH_GET_DATA_SUCCESS: 'FETCH_GET_DATA_SUCCESS',

    ADD_DATA: 'ADD_DATA',
    ADD_DATA_SUCCESS: 'ADD_DATA_SUCCESS',

    PUSH_DATA: 'PUSH_DATA',
    PUSH_DATA_SUCCESS: 'PUSH_DATA_SUCCESS',

    FILL_DETAIL_DATA: 'FILL_DETAIL_DATA',
    FILL_DETAIL_DATA_SUCCESS: 'FILL_DETAIL_DATA_SUCCESS'
};

export default AppAction;
